const lists = {
  A7: {
    one: ["race", "I will run the race with Uncle Ricky."],
    two: ["gave", "Ebony gave Raquel a birthday gift."],
    three: ["make", "Would you like to make an apple pie with me?"],
    four: [
      "age",
      "If someone asks your age, they want to know how old you are.",
    ],
    five: ["late", "If we don't hurry, we'll be late for school."],
    six: ["rake", "In the fall, I like to rake leaves."],
    seven: ["fun", "We had fun at the beach."],
    eight: ["but", "The weather was rainy but we still had a great time."],
    nine: ["brave", "The brave firefighter rescued the dog."],
    ten: ["space", "An astronaut is a person who travels in space."],
  },
  B7: {
    one: ["tree", "We have a tall tree in our backyard."],
    two: ["eat", "Would you like to eat dinner with us?"],
    three: ["lady", "The lady at the bank gave me a sticker."],
    four: ["baby", "The little baby slept in the crib."],
    five: ["beak", "A toucan is a bird with a very colourful beak."],
    six: ["read", "Emily likes to read under the covers with a flashlight."],
    seven: ["keep", "I always keep some money in my jacket pocket."],
    eight: ["free", "Harrison has a coupon for a free hotdog."],
    nine: ["only", "Kenneth is the only one who didn't come to the party"],
    ten: ["deep", "The deer wandered deep into the woods"],
  },
  B9: {
one: ["home", "There is no place like home."],
    two: ["nose", "My nose feels cold."],
    three: ["joke", "Suki likes to joke around with her friends."],
    four: ["own", "I have my very own scooter."],
    five: ["also", "Jayden likes to play chess, but he also likes checkers."],
    six: ["boat", "Samara sailed a boat across the ocean."],
    seven: ["goal", "Hailey scored the winning goal in the hockey game."],
    eight: ["foam", "The new foam in my chair makes it extra soft."],
    nine: ["snow", "I like to go sledding in the snow."],
    ten: ["bowl", "I can't believe we ate the whole bowl of watermelon."],
},
B10: {
one: ["crab", "When the crab pinched my sister she began to cry."],
    two: ["black", "Gabriella's favorite color is black."],
    three: ["snap", "Snap peas are my favorite to eat in the summer."],
    four: ["brush", "You should brush your teeth after every meal."],
    five: ["sweep", "I like to sweep the floor with the yellow broom."],
    six: ["flame", "The flame was able to light all the candles."],
    seven: ["grams", "Lisa was surprised at how many grams the orange weighed."],
    eight: ["trip", "Mindy just got back from her trip and has pictures to show us."],
    nine: ["fast", "I have never seen Matthew run so fast."],
    ten: ["fact", "Christopher only knows one fact about volcanoes."],
eleven: ["sight", "The lion had the zebra in its sight."],
    twelve: ["eye", "Keep an eye on the baby while I am gone."],
thirteen: ["nine", "I get to go on the big rides when I turn nine."],
fourteen: ["stove", "Their stove is always messy after cooking."],
fifteen: ["swimming", "Lamar did such a good job swimming this year"],
},
  C2: {
    one: ["wrench", "here is a sentence"],
    two: ["metal", "Stike the metal with your hammer"],
  },
  C3: {
    one: ["meow", "the cat meows"],
    two: ["barks", "the dog barks"],
  },
  C7: {
    one: [
      "toys",
      "Tirzah's favorite toys are her stuffed elephant and stuffed cat. ",
    ],
    two: [
      "soil",
      "The land has rich soil and will be good for planting crops. ",
    ],
    three: [
      "destroy",
      "A tornado is so powerful that it could destroy houses and property. ",
    ],
    four: [
      "point",
      "The mother asked her baby to point to the lion in the picture book. ",
    ],
    five: [
      "avoid",
      "If you want to avoid getting a cold, make sure you wash your hands often.",
    ],
    six: ["voice", "Anwell likes to sing and has a really beautiful voice. "],
    seven: [
      "loyal",
      "Some people say that dogs are the most loyal companions. ",
    ],
    eight: [
      "noise",
      " It's difficult for Daniel to concentrate on his book when there's a lot of noise. ",
    ],
    nine: [
      "voyage",
      "Hundreds of years ago, a voyage across the ocean was difficult and dangerous. ",
    ],
    ten: [
      "annoy",
      "It is very hard to annoy Dr. Anderson. He is a very patient person. ",
    ],
    eleven: ["broil", "Biyu placed the fish in the oven to broil. "],
    twelve: ["boy", "Mrs. Vacanti gave birth to a healthy baby boy. "],
    thirteen: [
      "coins",
      "Do you have enough coins to operate the laundry machine? ",
    ],
    fourteen: ["join", "Bethany wants to join the swim team. "],
    fifteen: ["joyful", "The holiday season is a joyful time of year. "],
    sixteen: [
      "rescue",
      "The Amboni family wants to rescue horses and endangered farm animals. ",
    ],
    seventeen: ["computer", "Stephen is playing a game on the computer. "],
    eighteen: ["fruit", "Aunt Sandy brought a fruit tart for dessert. "],
    nineteen: ["poisonous", "A rattlesnake is a type of poisonous snake."],
    twenty: ["enjoyable", "Carmen said the jazz concert was very enjoyable. "],
  },
  C9: {
one: ["golfer", "Uncle Matthew is a really good golfer."],
    two: ["felt", "Lisa cut a heart shape from a piece of pink felt."],
    three: ["farmer", "The farmer gets up before sunrise every day to begin his work."],
    four: ["full", "I'm so full, I can't eat another bite!"],
    five: ["feelings", "If you hurt someone's feelings, the right thing to do is apologize."],
    six: ["family", "How many people do you have in your family?"],
    seven: ["cough", "Dustin has had a cough for the past couple of days."],
    eight: ["enough", "Can you spot the difference between the two pictures? "],
    nine: ["roof", "The roof on the Jenkins' house is crumbling and needs to be replaced."],
    ten: ["rough", "Sand paper has a rough texture."],
eleven: ["forgetful", "Theresa can be forgetful sometimes, so she tries to write important things down."],
    twelve: ["fashion", "When Gabriella grows up she wants to be a fashion designer."],
thirteen: ["photograph", "Demarco found an old photograph of his grandfather in the attic."],
fourteen: ["tough", "Mr. Driscoll did not enjoy his dinner because the meat was too tough."],
fifteen: ["phrase", "Jason can say a phrase or two in French."],
sixteen: ["noise", "Spencer isn't allowed to get a pet bird because they make too much noise."],
seventeen: ["destroy", "A hurricane can potentially destroy many homes, businesses, and properties."],
eighteen: ["voice", "Be careful that you use your indoor voice when you are in the art gallery."],
nineteen: ["paragraph", "Reba needs to rewrite her paragraph to fix the mistakes in it."],
twenty: ["difference", "Can you spot the difference between the two pictures? "],
},
C10: {
one: ["spill", "Amy cried because she was sad to spill her ice cream cone on the ground."],
    two: ["berry", "Lindsay's mom made her a berry smoothie as an after-school snack."],
    three: ["happy", "Lucy was happy to pick out a new book from the library."],
    four: ["really", "The roads are really icy, so all drivers are advised to drive carefully."],
    five: ["messy", "Makeeda's room was messy, so her father asked her to clean it."],
    six: ["lettuce", "Would you like some lettuce on your sandwich?"],
    seven: ["carrot", "Bryce's mother chopped a carrot to add to the soup."],
    eight: ["puzzle", "Ariel received a 500-piece puzzle for her birthday."],
    nine: ["traffic", "We were late to the meeting because there was a lot of traffic."],
    ten: ["pizza", "On Friday nights, the Garcia family orders a pizza."],
eleven: ["errand", "Shaniqua's mom needs to run an errand before she goes home."],
    twelve: ["litter", "Paul is in charge of changing the cat litter as one of his chores."],
thirteen: ["address", "Will you please send me your new mailing address?"],
fourteen: ["collect", "Nathaniel has begun to collect coins from different countries."],
fifteen: ["happen", "What do you think is going to happen at the end of the movie?"],
sixteen: ["however", "We were going to take a road trip over the summer; however, we decided to stay home instead."],
seventeen: ["about", "I wonder what the new movie is going to be about."],
eighteen: ["flower", "Christine pressed a flower between the pages of her book."],
nineteen: ["successful", "Mr. Kodam is a successful businessman."],
twenty: ["necessary", "It is necessary to have a hall pass if you are going to be walking through the school hallways during class time."],
},
C11: {
one: ["daisy", "Marisol showed her brother how to make a daisy chain."],
    two: ["vase", "Miss Giordano keeps her special vase in the china cabinet."],
    three: ["plastic", "Jayla recycles all of her plastic water bottles."],
    four: ["zipper", "Make sure you zipper your jacket before you play outside, Mitchell's mom said."],
    five: ["reuse", "Michael's parents put their groceries in a canvas bag so they can reuse it every time."],
    six: ["sense", "It doesn't make sense to wear a winter jacket in the middle of the summer."],
    seven: ["does", "Does the supermarket close earlier on Sundays?"],
    eight: ["licence", "Ella wants to get her driver's license as soon as she turns sixteen."],
    nine: ["closet", "I think it's time to clean out the closet."],
    ten: ["season", "What is your favorite season?"],
eleven: ["bicycle", "Shane bought a bicycle at a yard sale with his allowance money."],
    twelve: ["distance", "Can you tell me the distance between the bank and the post office?"],
thirteen: ["service", "Eighth grade students must complete ten hours of community service."],
fourteen: ["classes", "The local bakery is going to start offering cupcake decorating classes."],
fifteen: ["yesterday", "Yesterday, Adelaide lost her first tooth."],
sixteen: ["fashion", "Abbey likes to pretend she's a fashion model."],
seventeen: ["photograph", "Mr. and Mrs. Clayborne have their wedding photograph on the wall in the living room."],
eighteen: ["enough", "Jayden has enough clothes for the winter."],
nineteen: ["sincerely", "One way to sign a friendly letter is by using the word sincerely and your name."],
twenty: ["citizen", "The senior citizen center has a bingo night every Wednesday."],
},
  D2: {
    one: ["costume", "Ella was excited to try on her Halloween costume"],
    two: ["swift", "Charlie made a swift recovery"],
    three: ["cotton", "Is that shirt made from cotton ?"],
    four: ["imitate", "Malik likes to imitate his older sister."],
    five: [
      "suddenly",
      "After the storm a rainbow suddenly appeared in the sky.",
    ],
    six: [
      "building",
      "The tallest building in the city is located on the Elm Street.",
    ],
    seven: ["kitchen", "The restaurant's kitchen was spotless."],
    eight: ["cousin", "Next month our cousin is getting married."],
    nine: ["window", "My cat likes to sit in the front window."],
    ten: ["shock", "Mara was in shock after she won the lottery."],
    eleven: ["fling", "Watch Chloe fling the Frisbee across the yard!"],
    twelve: ["crunch", "I heard the fall leaves crunch beneath my feet."],
    thirteen: ["shrimp", "Grilled shrimp is one of my favorite foods."],
    fourteen: ["switch", "The light switch was stuck in the off position."],
    fifteen: ["fudge", "Around the holidays my mom makes chocolate fudge."],
    sixteen: ["prompt", "The delivery man was prompt and courteous."],
    seventeen: ["olive", "Rosa likes to use olive oil when she is cooking."],
    eighteen: [
      "follower",
      "My parents always tell me to be a leader, not a follower.",
    ],
    nineteen: ["octopus", "An octopus has eight legs."],
    twenty: [
      "important",
      "The important document must be mailed by Wednesday afternoon.",
    ],
    twentyone: ["twister", "A twister is another name for a tornado."],
    twentytwo: ["plump", "Evan offered me a plump, red apple."],
    twentythree: [
      "stomp",
      "When she was a toddler, Angela would stomp her feet when she was angry.",
    ],
    twentyfour: [
      "chimpanzee",
      "The zookeeper wrapped the baby chimpanzee in a tiny blanket.",
    ],
    twentyfive: [
      "obstacle",
      "Avery completed the obstacle course in record time.",
    ],
  },
  D7: {
    one: ["throne", "The queen sat on her beautiful throne."],
    two: ["highway", "My GPS told us to turn onto the highway."],
    three: ["mobile", "Aiden bought me a new mobile phone."],
    four: [
      "recognize",
      "My cousin looked so different that I didn't even recognize her.",
    ],
    five: [
      "mileage",
      "Kiera's new pickup truck gets better mileage than her old one.",
    ],
    six: ["grown", "Carson has grown up so quickly."],
    seven: ["lighten", "This new furniture should lighten up the room."],
    eight: [
      "online",
      "Asher wanted to know when the movie started, so he looked it up online.",
    ],
    nine: [
      "boast",
      "My next-door neighbor likes to boast about his children's accomplishments.",
    ],
    ten: ["reply", "Easton still hasn't sent a reply to my email."],
    eleven: [
      "oldest",
      "Are you the oldest or the youngest child in your family?",
    ],
    twelve: [
      "throat",
      "Before he began speaking, Mr. Jung cleared his throat.",
    ],
    thirteen: [
      "stolen",
      "Someone has stolen the little frog statue in my garden!",
    ],
    fourteen: [
      "toaster",
      "My new toaster can toast four slices of bread at once.",
    ],
    fifteen: [
      "frightening",
      "Walking through the haunted house sure was a frightening experience",
    ],
    sixteen: ["poet", "My favorite poet is Shel Silverstein."],
    seventeen: [
      "thrive",
      "Petunias and impatiens always thrive in Mr. Nelson's garden.",
    ],
    eighteen: ["icicle", "That's a huge icicle on the side of the house."],
    nineteen: ["tonight ", "Tonight I am going to the theater with Kylie."],
    twenty: [
      "whole",
      "That sub was humongous, and I can't believe you ate the whole thing yourself.",
    ],
    twentyone: ["crooked", "The picture on the wall is still crooked."],
    twentytwo: ["sugar", " The secret ingredient is brown sugar."],
    twentythree: ["bushel", "We bought a bushel of peaches for only $20."],
    twentyfour: [
      "exercise",
      "Kennedy and Skylar like to exercise on the beach.",
    ],
    twentyfive: [
      "licence",
      "When he turns 16, my brother will get his driver's licence.",
    ],
  },
  D9: {
one: ["bounce", "My little sister liked to bounce up and down on her pogo stick."],
    two: ["frown", "Junie has a frown on her face because she's unhappy."],
    three: ["mountain", "There is snow on the peak of the mountain."],
    four: ["drawn", "Mrs. Wellington keeps all the curtains in her house drawn."],
    five: ["false", "On the test, we had to tell which statements were true, and which were false."],
    six: ["couch", "Levi fell asleep on the couch when he came home from soccer practice."],
    seven: ["howling", "The coyotes are howling."],
    eight: ["always", "Mr. Wong always locks his car doors."],
    nine: ["scouted", "I scouted the valley in search of the perfect camp site."],
    ten: ["sauce", "Lynn makes the most delicious spaghetti sauce I've ever tasted."],
eleven: ["pounce", "The kitten pounced on the toy mouse."],
    twelve: ["coleslaw", "Coleslaw is made from cabbage, mayonnaise, and carrots."],
thirteen: ["squawk", "I heard a crow squawk in the backyard."],
fourteen: ["awful", "My dog made an awful mess of the kitchen floor."],
fifteen: ["sprout", "When spring comes, daffodils will sprout from the ground."],
sixteen: ["scrounge", "The dogs scrounge for food behind the restaurant."],
seventeen: ["awning", "Let's have lunch outside below the awning."],
eighteen: ["slouch", "Samantha tries not to slouch when she is sitting at the dinner table."],
nineteen: ["aloud", "Anthony read part of his essay aloud to the class."],
twenty: ["jigsaw", "We've almost completed this 500-piece jigsaw puzzle."],
twentyone: ["mobile", "Eleanor and Jason bought a mobile home."],
twentytwo: ["recognize", "You've grown so much I almost didn't recognize you."],
twentythree: ["throat", "Do have have a sore throat?"],
twentyfour: ["tomahawk", "A tomahawk is a lightweight ax invented by Native Americans."],
twentyfive: ["roundabout", "The city installed a new roundabout to ease their traffic problem."],
},
D10: {
one: ["officer", "Cameron wants to be a police officer like his dad."],
    two: ["arrival", "Mr. and Mrs. Nolan are excited for the arrival of their baby boy."],
    three: ["approve", "Mrs. Sanders doesn't approve of her boys riding their bikes without wearing helmets."],
    four: ["toolbar", "You can change the way the words on your computer look by using the toolbar."],
    five: ["offend", "Felicity didn't mean to offend Tessa when she pointed out the crumb on Tessa's shirt."],
    six: ["worried", "Jason's mother was worried that they'd be late to his dentist appointment."],
    seven: ["succeed", "I know you will succeed in whatever you put your mind to."],
    eight: ["warrior", "Jaylen pretends to be a samurai warrior when he plays in the backyard."],
    nine: ["mirror", "Would you please clean the mirror? It's so dusty, I can hardly see anything through it!"],
    ten: ["grammar", "Some of the rules of grammar are difficult to remember."],
eleven: ["cabbage", "Lorna's family has corned beef and cabbage for dinner on St. Patrick's Day."],
    twelve: ["traffic", "Can you believe how much traffic there is on the road this morning?"],
thirteen: ["scanner", "Ciara made a copy of the document using the computer scanner."],
fourteen: ["career", "What kind of career would you like to have when you grow up?"],
fifteen: ["swollen", "When Lonisa has allergy symptoms, her eyes become swollen and puffy."],
sixteen: ["proceed", "'If there are no questions, we will proceed,' said the teacher."],
seventeen: ["equally", "Paul and Quinn worked on their partner history report equally."],
eighteen: ["install", "Today the maintenance man is going to install a new water fountain in the hallway."],
nineteen: ["fitness", "Wanda is a fitness instructor at the local gym."],
twenty: ["glimmer", "The ornaments on the Christmas tree glimmer among the twinkling lights."],
twentyone: ["became", "The caterpillar became a beautiful butterfly."],
twentytwo: ["surprise", "Chun organized a surprise birthday party for his friend, Jian."],
twentythree: ["include", "Penny makes sure to include her little brother in the games she and her friends play."],
twentyfour: ["accidental", "José made an accidental hole in his shirt when he used scissors to cut the tag off."],
twentyfive: ["occupied", "Please knock on the bathroom door in case the bathroom is already occupied."],
},
  E7: {
    one: [
      "monkeys",
      "The scientist studied the monkeys in their natural habitat.",
    ],
    two: ["knives", "The blades of those kitchen knives need to be sharpened."],
    three: [
      "thieves",
      "That area was well known for being saturated with common thieves.",
    ],
    four: [
      "tomatoes",
      "There is nothing better than homegrown tomatoes in a summer salad!",
    ],
    five: [
      "oxen",
      "The oxen were strong and healthy animals, so they fetched a high price at the market.",
    ],
    six: [
      "addresses",
      "The school campus was so large that it actually had several addresses.",
    ],
    seven: [
      "puppies",
      "Newborn puppies must stay with their mother until they are old enough for adoption.",
    ],
    eight: [
      "families",
      "Every Sunday, the families would gather together and distribute food to the needy.",
    ],
    nine: [
      "roofs",
      "In many African village communities, people build simple homes with thatched roofs.",
    ],
    ten: [
      "radios",
      "Radios emit unpleasant static if they cannot pick up a strong enough signal.",
    ],
    eleven: [
      "potatoes",
      "Did you know there are more than 4,000 varieties of native potatoes in the world?",
    ],
    twelve: [
      "geese",
      "My father always gets frustrated when the geese make a mess on the golf course.",
    ],
    thirteen: [
      "loaves",
      "The baker arranged the fresh loaves of bread in the display case to tempt customers.",
    ],
    fourteen: [
      "batteries",
      "I cannot believe that toy requires so many batteries in order to operate!",
    ],
    fifteen: [
      "shelves ",
      "The pantry shelves in the kitchen were lined with a large collection of herbs and spices.",
    ],
    sixteen: [
      "wives",
      "The wives gathered together in the living room, laughing, chatting, and drinking tea.",
    ],
    seventeen: [
      "pennies",
      "Kayla found three shiny pennies on the ground and put them in her pocket for luck.",
    ],
    eighteen: [
      "bakeries ",
      "Nina always knows about the best bakeries in the city; she has quite a sweet tooth!",
    ],
    nineteen: [
      "lenses ",
      "The sunglasses my cousin bought yesterday had one of the lenses fall out already!",
    ],
    twenty: [
      "intestines",
      "The boy learned the importance of the stomach and the intestines in human digestion.",
    ],
    twentyone: [
      "explorer",
      "Gregory spent the hot summer days pretending to be a brave explorer in a new land.",
    ],
    twentytwo: [
      "quarter ",
      "Mom let Casey put a quarter into the gumball machine to retrieve his yummy treat.",
    ],
    twentythree: [
      "porch ",
      "My mother and father love to sit on the porch and drink their coffee in the mornings.",
    ],
    twentyfour: [
      "criteria",
      "I don't believe the judges are using fair criteria to assess the performers' auditions.",
    ],
    twentyfive: [
      "alumni",
      "The school will host its annual “alumni weekend” this month ",
    ],
  },
  E9: {
one: ["lightning", "The flash of lightning was followed by a loud rumble of thunder."],
    two: ["yacht", "The big, beautiful yacht sat in the water, ready for its first trip out to sea."],
    three: ["condemn", "Before you condemn me for doing something wrong, listen to what I have to say."],
    four: ["assignment", "The book report assignment is due at the end of the week."],
    five: ["plumber", "Luke learned all he needed to know about being a plumber from his dad."],
    six: ["crumb", "Irene ate every last piece of the cake. She didn't even leave a single crumb."],
    seven: ["knife", "Beatrice watched her dad chop vegetables with a knife."],
    eight: ["calf", "Did you know that a baby whale is called a calf?"],
    nine: ["whistle", "When the dog hears the sound of the whistle, he comes running back to his owner."],
    ten: ["autumn", "Samir checked the calendar because he forgot which day was the first day of autumn."],
eleven: ["flight", "I'm worried that my flight will be canceled because of the bad weather."],
    twelve: ["resign", "The city mayor suddenly decided to resign from his position."],
thirteen: ["lamb", "Eleanor learned how to play “Mary Had a Little Lamb” on the piano."],
fourteen: ["climb", "Some people climb all 1,576 steps to the top of the Empire State Building."],
fifteen: ["castle", "Michelle's favorite story is about a princess, a brave night, and a magical castle."],
sixteen: ["honorable", "Chad's mom taught him to do the honorable thing by helping others in need."],
seventeen: ["kneel", "Grandma can no longer kneel on the ground to garden because of her sore knees."],
eighteen: ["rhythm", "It is difficult for me to keep a steady rhythm in music class."],
nineteen: ["butcher", "Our town is so small that we only have one local butcher selling meat."],
twenty: ["character", "Today we are going to discuss the personality of the main character in the story."],
twentyone: ["shelves", "Brooke made clever book shelves for her new house by using old crates and pallets."],
twentytwo: ["lenses", "Thomas needs the lenses in his glasses replaced with ones that aren't scratched."],
twentythree: ["batteries", "It seems like these batteries don't last as long as they should!"],
twentyfour: ["debris", "The tornado left behind a lot of damage and debris."],
twentyfive: ["psychology", "Vicky wants to study psychology when she goes to college someday."],
},
E10: {
one: ["anchor", "The captain dropped the anchor down to keep the boat in one place."],
    two: ["vinegar", "Patrick's mom uses vinegar in some of her recipes."],
    three: ["whimper", "The dog let out a soft whimper when she realized she was going to the vet."],
    four: ["cylinder", "In math class, you will learn to calculate the volume of a cylinder."],
    five: ["ancestor", "An ancestor is someone in your family line who lived long before you."],
    six: ["neighbor", "Leah has a new neighbor in her apartment building."],
    seven: ["counselor", "One role of a guidance counselor is to help older students make choices about college."],
    eight: ["narrator", "Jennifer is going to play the part of the narrator in the school drama."],
    nine: ["believer", "Nora would describe herself as a believer in miracles."],
    ten: ["lighter", "Now that the rain has stopped, the sky has become lighter and the clouds have cleared."],
eleven: ["carrier", "Kyle's older brother is a mail carrier for the United States Postal Service."],
    twelve: ["grammar", "Draden has always been a quick learner when it comes to spelling and grammar."],
thirteen: ["elevator", "A sign in front of the elevator said, Out of order."],
fourteen: ["censor", "Some governments censor, or ban, certain types of books, music, and movies."],
fifteen: ["discolor", "I wonder if washing my new shirt in hot water will discolor the fabric?"],
sixteen: ["educator", "Mr. Shepherd has been an art educator for fifteen years."],
seventeen: ["projector", "Mrs. Frederick turned on the classroom projector so we could see the image of the map."],
eighteen: ["triangular", "The Egyptian pyramids are a real-life example of triangular prisms."],
nineteen: ["solar", "Chase's family has installed new solar panels on the roof of their house."],
twenty: ["laser", "Troy wants to invite his friends to play laser tag for his ninth birthday party."],
twentyone: ["college", "Students from the local college presented their invention at a national conference."],
twentytwo: ["lotion", "The beauty store gave away small samples of their new brand of hand lotion."],
twentythree: ["general", "In general, the more you study for your tests, the better prepared you will be for them."],
twentyfour: ["survivor", "Ulana's aunt is a survivor of cancer. "],
twentyfive: ["sorcerer", "In the movie, the main character must defeat the evil sorcerer."],
},

};





















//Shells for building out the word lists
// C2: {
// one: ["", ""],
//     two: ["", ""],
//     three: ["", ""],
//     four: ["", ""],
//     five: ["", ""],
//     six: ["", ""],
//     seven: ["", ""],
//     eight: ["", ""],
//     nine: ["", ""],
//     ten: ["", ""],
// eleven: ["", ""],
//     twelve: ["", ""],
// thirteen: ["", ""],
// fourteen: ["", ""],
// fifteen: ["", ""],
// sixteen: ["", ""],
// seventeen: ["", ""],
// eighteen: ["", ""],
// nineteen: ["", ""],
// twenty: ["", ""],
// twentyone: ["", ""],
// twentytwo: ["", ""],
// twentythree: ["", ""],
// twentyfour: ["", ""],
// twentyfive: ["", ""],
// },
